### ISSUE TITLE
bfdia 5b the explore button is not loading can you help me fix it please

### ISSUE THREAD

**Issue by Jflynn111** [coppersalts/HTML5b#15]

**Comment by Jflynn111** [comment]
hope you see this comment

**Comment by Jflynn111** [comment]
its just not loading and i don't know how to fix it

**Comment by Zolo101** [comment]
ive fixed it, but it could still happen again in the near future...

its due to 5beam's upload validator not catching everything, and html5b crashing if it shows a broken level in explore :(

**Comment by Jflynn111** [comment]
ok

**Comment by Jflynn111** [comment]
um sadly it happend again so can you tell me how to fix it that way I always don't have to ask you to do it

**Comment by Zolo101** [comment]
> can you tell me how to fix it that way I always don't have to ask you to do it
the problem always occurs server-side so unfortunately im the only one who can fix it :(
this time though it was definitely my fault, i was updating my website and i had to change some stuff, which accidently stopped the server from loading levels

but its fixed now, so thx for telling me so quickly!

**Comment by Zolo101** [comment]
next time i change something on the server i'll warn everyone in the 5b Central discord beforehand

**Comment by Jflynn111** [comment]
ok your welcome have a good night :)

**Comment by Jflynn111** [comment]
hi so the explore button is not working again as always so whenever you have time would you mind fixing it again please just wanted to let you know

**Comment by Zolo101** [comment]
fixed! im currently working on a server-side update (hopefully released on march 4th) that will block corrupted levels from being uploaded, so that this wont happen again

**Comment by Jflynn111** [comment]
ok thank you if it does happen again I'll let you know

**Comment by Jflynn111** [comment]
explore is takeing a long time to load so it might need to be fixed again

**Comment by Jflynn111** [comment]
so explore is sorta working and sort of not when i click it the first page is working fine but when i turn the page it just takes forever to load again
