### ISSUE TITLE
Start button does not function propperly

### ISSUE THREAD

**Issue by Icywastaken** [coppersalts/HTML5b#16]
The problem is the start button does not start the game at all when i press it

I am on a mobile device and have attached a fully functioning bluetooth keyboard to my device

**Comment by coppersalts** [comment]
There is currently no code to handle pressing buttons on mobile.

**Comment by Icywastaken** [comment]
Goodness that was a fast reply, oh well it shouldnt be too hard to add, right?

**Comment by coppersalts** [comment]
Yes, probably. Once I get back to actually developing it again I can start looking into it, but for now it's only really playable on a computer.

**Comment by Zolo101** [comment]
@Icywastaken can you try https://zolo101.github.io/HTML5b/ and see if it works?

**Comment by Icywastaken** [comment]
Oh het it actually works, thank you ^_^
