### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by viewerlikeu** [coppersalts/HTML5b#25]
Hi! Was just hoping you could add a license to this project. Considering [5b itself](https://github.com/carykh/5b) is GPL 3, it's as simple as adding the same license file to the repo. It appears you and @Zolo101 are the only contributors, so as long as you're both ok with it, would be appreciated. :)

**Comment by coppersalts** [comment]
I'd be down for this. Although Zelo has only contributed a bit of code to HTML5b relating to the 5beam rewrite, I'd still want to check with him first.

**Comment by Zolo101** [comment]
I'm alright with this aswell 👍

**Comment by coppersalts** [comment]
added it
