### ISSUE TITLE
Html5b not loading at all

### ISSUE THREAD

**Issue by discoveryX64** [coppersalts/HTML5b#27]
I go to play the game and all I'm stuck with is a "Loading..." text.
<img width="968" alt="Screenshot 2024-02-06 at 10 33 11 PM" src="https://github.com/coppersalts/HTML5b/assets/119447512/fcd9f364-0902-4c8d-b46d-c2d1e3db6c44">

**Comment by discoveryX64** [comment]
Also is there a way to export it after I get it working?

**Comment by coppersalts** [comment]
If you downloaded it, try going to the web url instead (coppersalts.github.io), and if you're having this problem there it may be fixed by waiting. I'm not sure what you mean by export; can you clarify what you mean there?

**Comment by discoveryX64** [comment]
Exporting as in adding it to another webpage or something along those lines. When I cleared my browser cache it seemed to work. I will probably just fork it in the meantime and redirect my other website to the fork because when I use yours it has sizing issues. Thanks for porting this masterpiece.

**Comment by discoveryX64** [comment]
Usually using the site in iframes and trying to crop it. Sorry for the late response. I'll close this ticket now since what I was asking for was kind of useless. Hope you have a good time copper!
