### ISSUE TITLE
tile rendering weirdness

### ISSUE THREAD

**Issue by PoleyMagik** [coppersalts/HTML5b#3]
-border seems to be misaligned alot of the time
-every 2 tiles (horizontally and vertically) appear misaligned

![image](https://user-images.githubusercontent.com/59105820/181047675-c21597e4-6e54-4673-8bcf-a3ce86422b7e.png)

**Comment by coppersalts** [comment]
Would you happen to have the page zoomed in? This in known to happen when you zoom in the browser.

**Comment by PoleyMagik** [comment]
> Would you happen to have the page zoomed in? This in known to happen when you zoom in the browser.

no, zoomed out.

**Comment by coppersalts** [comment]
The only reason I can think of for this happening is the `pixelRatio` variable being set to some non-integer value. Which I only know of being caused by changing the zoom on the browser. So if `pixelRatio` isn't one of its normal values (1 or 2) this is what I would expect.

**Comment by PoleyMagik** [comment]
Hm, for some reason my browser full zoomed out is giving me a pixelRatio of 1.25? This is very strange.
![image](https://user-images.githubusercontent.com/59105820/181281909-2e8f5723-6818-4df8-a2e8-2d51a4e463a2.png)
Strangely, zooming to 200% seems to fix this issue. Very strange. I'm using the latest version of chrome just for clarification, ik in the screenshot it says it's pending an update, but I also tried on the latest version, error still occuring.

**Comment by coppersalts** [comment]
I think I found an article on this, but I don't use windows, so I can't test it.
[https://danreynolds.ca/tech/2017/10/15/Variable-Browser-Zoom/](https://danreynolds.ca/tech/2017/10/15/Variable-Browser-Zoom/)

**Comment by PoleyMagik** [comment]
I have tested what they mentioned in the article, and yes, their code does indeed fix this issue. Changes the size of the page, but it's not a big deal, 100% to 80% isn't a big problem.

**Comment by coppersalts** [comment]
Implemented it in the most recent update.
